### ISSUE TITLE
Codes.keys :home and :end aren't correct on my platform.

### ISSUE THREAD

**Issue by jemc** [piotrmurach/tty-reader#1]
While working on building some neat stuff with your libraries, I noticed that `Code.keys[:home]` and `Codes.keys[:end]` are not correct/working for my platform.

You currently have them as: https://github.com/piotrmurach/tty-reader/blob/aa2213d4ac16a26cadba53417d44e741d6d4b190/lib/tty/reader/codes.rb#L47-L52

But on my keyboard, on my 64-bit Linux distro, they are actually:
```ruby
home:      "\e[H",
insert:    "\e[2~",
delete:    "\e[3~",
end:       "\e[F",
page_up:   "\e[5~",
page_down: "\e[6~",
```

I'm not sure how to resolve this, because I'm sure your codes worked for you, but they don't work for me.

**Comment by piotrmurach** [comment]
I'm not surprised that the `:home` and `:end` codes don't work. Originally, I focused on `:insert` and `:delete` keys to ensure they work cross platform and neglected fully testing the `:home` and `:end`. The compatibility of terminal emulators is a bit wishy washy. I was working with `vt220` emulator standard and got my codes from a document (see [vt220 spec](http://manx-docs.org/mirror/vt100.net/dec/ek-vt220-rm-001.pdf) page 34) When you read the standard, for example, the `f1-f12` codes, it leaves `f1-f4` to local specification and this leads to some incompatibility which is reflected in a way in my codes file where I have `f1` for linux and `f1_xterm` for mac. The `home: "\e[H"` makes sense as this is what I use in `tty-cursor` to move cursor in horizontal line to a given position, without specifying any number it clearly moves to the first column. What I would do is to rename the `:home => :find` and `:end => :select` with the current codes and use your `:home` and `:end` codes.

```ruby
home: "\e[H"
end: "\e[F"
find: "\e[1~"
select: "\e[4~"
````

We could also add the `bell: "\a"` virtual key which can be handy when performing completions that have no match. Do you fancy submitting PR?

I'm also thinking if it wouldn't be worth to split `keys` into `linux_keys` and `mac_keys`? The virtual keys maps are different between all three operating systems with some overlaps.

**Comment by jemc** [comment]
I did the `:home`/`:end`/`:find/`:select` changes in #3.

I tried to add `:bell`, but it conflicted with `:ctrl_g`, so I left it out.

> I'm also thinking if it wouldn't be worth to split keys into linux_keys and mac_keys? The virtual keys maps are different between all three operating systems with some overlaps.

My main concern is that the application using the `KeyEvent` API shouldn't have to be aware of the platform. If it's possible to do what you describe and keep that requirement, it sounds fine with me.

**Comment by piotrmurach** [comment]
> My main concern is that the application using the KeyEvent API shouldn't have to be aware of the platform. If it's possible to do what you describe and keep that requirement, it sounds fine with me.

The `tty-reader` currently does that already, namely, auto detects the windows vs unix situation to choose appropriate virtual key codes. However, for the moment I think this is good enough. So let's focus our efforts on the completion aspect.
