### ISSUE TITLE
Can I use tty-reader and tty-pager at the same time?

### ISSUE THREAD

**Issue by vemv** [piotrmurach/tty-reader#10]
Hey there,

I'm figuring out if a certain idea is feasible, wouldn't want to waste time blindly giving it a shot.

I want a pager application where 'shortcuts' (single-key keypresses: <kbd>left</kbd> or <kbd>a</kbd>) alter the output (e.g.: I'm paging a file, I hit <kbd>a</kbd>, now I'm paging some other file).

Can that be achieved with tty-reader and tty-pager?

One could imagine that while the pager is on, no arbitrary keypresses are being listened to. Maybe I'm wrong.

Cheers - Victor

**Comment by piotrmurach** [comment]
Hey Victor!

I would encourage you to give it a shot! TTY gems are built to be composable to create new tools. tty-reader is a generic inputs reader that you can use to build whatever needs to respond to key presses, for example your own repl. I use tty-reader recently for bulding terminal games.

As for tty-pager, there are two types of pagers, a system one, which calls out to external utility and a basic one built in pure Ruby. I would think that the system one won't match your requirement as it will be impossible to control paged output. On the other hand, the basic one with some tweaking may bring some good results.

I would suggest experimentation and if you build something please share it. Also, I'm accepting any PRs if you find you're missing someting from tty-pager or tty-reader and it would be a good addition.

**Comment by vemv** [comment]
Hi Piotr, gotchu!

Thanks for the explanation and encouragement.

Will report. ✌️
