### ISSUE TITLE
Doc Request: Differences with Readline

### ISSUE THREAD

**Issue by brandondrew** [piotrmurach/tty-reader#11]
I like that you're not beholden to ancient software that may not have made the right choices, but I'm also very curious to know _where_ and _how_ TTY-Reader differs from Readline.  Would you be willing to add an overview of those differences to the README?  I think it would be very useful to many people.

**Comment by piotrmurach** [comment]
Do you have time to investigate and submit PR? Source is super tiny and api has currently only a few methods. I'm super busy and currently maintaining many open source projects. I really would welcome help here! 🙏
