### ISSUE TITLE
:keydown press erases line even if history is disabled

### ISSUE THREAD

**Issue by cpence** [piotrmurach/tty-reader#20]
Hello!

I'm using tty-reader for a "search filter" line in a note-taking client, where typing live-updates a search field in the rest of the terminal. I've deactivated the history feature (as I don't need it), and have bound functions to `:keyup` and `:keydown` presses to scroll through the list (imagine a CLI version of Notational Velocity).

Unfortunately, the keypress of `:down` also erases the line (https://github.com/piotrmurach/tty-reader/blob/master/lib/tty/reader.rb#L259), and so scrolling erases what the user has typed into the field. I would think that line 259 should end with `if track_history?`.

Is there a reason for that default keybinding? It doesn't seem intuitive to me that the down-arrow erases the field even if history is disabled. At the very least, it'd be great to have a configuration setting that would turn off that behavior.

Thanks for an awesome collection of gems!

**Comment by piotrmurach** [comment]
Hi Charles,

Thanks for using `tty-reader` and I'm glad the collection of gems is serving your needs.

You're right this seems like a bug. Not sure why I settled for this behaviour originally but I agree that erasing input is less than intuitive. This should behave similar to `:up`, namely, retrieve the next item if it is present, otherwise do nothing with the input. Would you have time to submit PR, ideally with a test to ensure this change stays true for future releases.

**Comment by cpence** [comment]
I should be able to take a crack at that over the weekend, sure thing! Watch this space.

**Comment by cpence** [comment]
Turns out I had time to look at this tonight. I created a new spec because the subject needs different parameters, otherwise tried to copy style on the tests as best I could. Let me know what you think!

**Comment by cpence** [comment]
Coming back to close this issue, but is there any chance you could cut an 0.9 release with this change?

**Comment by piotrmurach** [comment]
I'll strive to release this asap and please bear with me as I need to make sure that this is working with `tty-prompt`. Your change has prompted me to think about the behaviour of the erasing line when tracking history. I added a buffer to make sure that user input is not lost (see https://github.com/piotrmurach/tty-reader/commit/8db5b85a6269489f6e6beffe95284fdf82d795cc). This should closely mirror shell behaviour and makes the `read_multiline` work better. I don't plan to make any more changes for this release but felt this change closely matched your work. Would you mind checking against master?

**Comment by cpence** [comment]
No worries! I like the idea of that feature, that's also exactly the kind of behavior someone would expect. It'll take me a bit to be able to test against master, but I'll try to report back soon.

**Comment by cpence** [comment]
Confirmed for my issue, at least, everything still looks great. Thanks!

**Comment by piotrmurach** [comment]
@cpence I was hoping to release a new version this weekend but instead got to work some more on the internals. One thing that I did is to switch to using explicit keyword arguments. There shouldn't be any breaking changes. Please see [changelog](https://github.com/piotrmurach/tty-reader/blob/master/CHANGELOG.md) for details. I'm done and need to do some final checks and will release shortly. One extra thing I'm considering for this release is the https://github.com/piotrmurach/tty-reader/pull/19 PR. Do you have any thoughts on it?

**Comment by cpence** [comment]
Seems like it would be an ever-so-slightly breaking change, insofar as it would require a `to_s` after any uses of `event.line`, but that's nothing super problematic as long as it's announced clearly. (Might need a major-version bump, though, to stick with semantic principles?)

**Comment by piotrmurach** [comment]
Agreed. I'm still not sure if exposing a line object in its current shape is the right thing to do. So I'm going to defer this change to the next release. I consider changes carefully and don't intend to make breaking changes, however, since this gem is below `1.0` I cannot rule out and 'reserve' the possibility for making any necessary changes.

**Comment by piotrmurach** [comment]
@cpence Released `v0.9.0`. Thanks for your contribution!

**Comment by cpence** [comment]
No worries, thanks for the help and the gems!
