### ISSUE TITLE
Home and End keys do not function properly

### ISSUE THREAD

**Issue by DannyBen** [piotrmurach/tty-reader#4]
(Continuing #3)

Seems like there is a problem with the `Home` and `End` keys.

This is my sample script:

```ruby
require 'tty-reader'
require 'readline'

puts "tty-reader"
reader = TTY::Reader.new
p "Received: " + reader.read_line

puts "----"

puts "rb-readline"
p "Recevied: " + Readline::readline
```

This is how it looks (pressing home and end simply does nothing, and the string stores some escape codes)

![anim](https://user-images.githubusercontent.com/2405099/33338122-b98ec4b2-d47d-11e7-984c-e52005c4b4da.gif)

This is the output (pasted here for reference):

```
tty-reader
home and end
"Received: home\e[1~ and end\e[1~\n"
----
rb-readline
home
"Recevied: home"
```

**Comment by piotrmurach** [comment]
I've changed how keys are recognised across different platforms. This is only available on master branch and hasn't been released yet. Would you have time to check if the `Home` and `End` keys work correctly. Thanks!

**Comment by DannyBen** [comment]
Sure. Will report back.

**Comment by piotrmurach** [comment]
Ohh dear... after all the work of adding the home & end keys for different systems I've forgotten to actually hook them up with `read_line`. These should work fine now, at least they do on my machine but curious to know how they work for you?

**Comment by DannyBen** [comment]
Success!

The only difference I see now is that TTY reader adds a newline whereas readlines does not.

[![asciicast](https://asciinema.org/a/3tFTTBq0TcSsz2syfZqHNE3uM.png)](https://asciinema.org/a/3tFTTBq0TcSsz2syfZqHNE3uM)

**Comment by piotrmurach** [comment]
Nice! Thanks for confirming.

The `tty-reader` is not really a copy of `readline`. The way I see it is that `Readline` is a unix tool that has it's own behaviour that may be different across systems. `tty-reader` tries to be closer to Ruby behaviour. In this instance, reading line with Ruby is done by:
```
$stdin.gets
```
which returns a new line on input as it is a valid 'Enter' character. The `#read_line` has toggle for `raw` mode. That's on by default to allow all the control keys, however when `raw` mode is disabled the input acts as `gets` where none of the characters are interpreted by shell.

**Comment by DannyBen** [comment]
Fair enough. Thanks for the beautiful set of `TTY::*` gems and their outstanding documentation. This is really a model set of gems. The issue can be closed as far as I am concerned.

**Comment by piotrmurach** [comment]
By all means please do submit ideas/suggestions/bugs, anything really. I want this library to be generic purpose input reader to help in building higher level libs. 

Thank you for your kind words! There is still many new tty gems to be released in the near future - keep your eyes peeled for any notices!
