### ISSUE TITLE
Esc keypress is not detected

### ISSUE THREAD

**Issue by saveriomiroddi** [piotrmurach/tty-reader#6]
The Esc keypress is not detected on my system (Ubuntu 16.04 x86-64).

In order to reproduce it, just execute:

    TTY::Reader.new.read_keypress

and type Esc - nothing will happen.

As a consequence of this, it's not possible to listen on :keyescape events.

**Comment by saveriomiroddi** [comment]
@piotrmurach as far as I read from the code, is the problem that Esc can be used for composing escape sequences, so that the reader waits for other keypresses after it reads it? If this is correct, is the fix to introduce an option to not support composable escape sequences?

**Comment by saveriomiroddi** [comment]
Hello Piotr!

I'm going to follow up here the discussion from #8, I think this is the best place. Since it's a quite complex subject. I'll break into approaches, hopefully it will be clear :smile: 

## blocking `getc` read + pure peeking

My original idea was similar to yours: I thought that the best/most compatible strategy (with the current approach) would have been to is to find a way to peek stdin:

- blocking read of the first character (`getc`)
- peeking one character, without actually reading (hypothetical `peek`)
- return the character if there's nothing in the buffer

Sadly, there is no such method provided by ruby - at least, I couldn't find any.

## blocking `getc` read + non blocking read (readahed)

The strategy you propose does work:

```ruby
puts STDIN.getc.inspect
begin
  puts STDIN.read_nonblock(1).inspect
rescue IO::EAGAINWaitReadable
  # nothing in the buffer
end
```

I guess that this "readahead" strategy would need to be applied only in the case where the escape character is detected.

On crucial assumption in this case is that an escape sequence never includes a multibyte character; if it did, the encoding would need to be handled, since `read_nonblock` returns a bytes sequence (without encoding), which would add some complexity.

## single `read_nonblock` read for any type of input

It does work, but requires encoding handling for any type of input, which adds complexity.

It has one advantage compared to `getc` (independetly from `read_nonblock`), which is that the entire escape sequence is returned at once, so there is no need to detect when an escape sequence ends.  
This is, at least, based on my tests on my machine - I have no idea how this works on anything other than Linux [Ubuntu]

## single `sysread` read for any type of input

This seems to be like `read_nonblock`, except that it blocks, so it would have its advantage(s), but still, requires dealing with the encoding.  
Again, this is based solely on my tests, I can't guarantee that this is the universal working.

## conclusion

blocking `getc` read + non blocking readahead seems to be the simplest change (if the multibyte assumption holds true).

If there would be a guaranteed solution for handling the encoding of low-level streams (and `sysread` assumptions would hold true), then entirely replacing `getc` (and the related escape detection logic) with `sysread` would be very advantageous, however, it requires experience on consoles.

Bye!

**Comment by piotrmurach** [comment]
This is some great research! Thanks for looking into this issue! 🙏

I will set aside some time to see how I can apply what you have already discovered. Stay tuned!

**Comment by cnorman-enphase** [comment]
This seems to work pretty well for me captures only 1 single keypress, including ESC!, on CentOS v7 with ruby 2.0.0.

def get_char
  begin
    system("stty raw -echo")
    str = STDIN.getc
  ensure
    system("stty -raw echo")
  end
  # print "#{str.chr.upcase} ✔" # optionally echo out the input in uppercase
  str.chr
end

**Comment by piotrmurach** [comment]
@saveriomiroddi Fixed the `Esc` key using the blocking `getc` read followed by non-blocking read if the previous character is preceded by escape key. So now you can listen for `:keyescape` events! This is the safetest option since `getc` will handle any multibyte encoding and escape keys are only followed by ascii set of characters.

Thanks again for looking into this and providing such great comment, without this it would be hard to fix! I completely forgot about this issue and just reviewing my tickets I've realised there is this important thing to do. Better late than not at all...

**Comment by saveriomiroddi** [comment]
> @saveriomiroddi Fixed the `Esc` key using the blocking `getc` read followed by non-blocking read if the previous character is preceded by escape key. So now you can listen for `:keyescape` events! This is the safetest option since `getc` will handle any multibyte encoding and escape keys are only followed by ascii set of characters.
> 
> Thanks again for looking into this and providing such great comment, without this it would be hard to fix! I completely forgot about this issue and just reviewing my tickets I've realised there is this important thing to do. Better late than not at all...

Wow thanks! Glad to help - this is a significant fix (at least for me!) :smile:
