### ISSUE TITLE
read_keypress blocking behavior

### ISSUE THREAD

**Issue by thewyzard44** [piotrmurach/tty-reader#7]
here's one for you...  and I 'suspect' although I'm not sure, that it's a platform issue(?)  I'm running latest windows 10 & ruby 2.4.3

when read_keypress is running/blocking/waiting for a keystroke...  I haven't been able to find a way to interrupt or cancel the call.  I've put it inside a Timeout block, and into a background thread that I attempt to kill.  Neither of which worked, so I just simply tried to kill my main thread and that didn't work either.  

The behavior is that my app continues to run after attempting the kill.  But upon the next keystroke THEN the Timeout exception (or the thread kill) bubbles up and terminates my app.

I have it working at the moment like this https://github.com/NexusSW/kitchen-lxd_nexus/blob/01bd6262cc9e20abeb7d0082998f62a05e0234cb/exe/lxc-shell#L64-L67 using the :nonblock option

but...  I would also like to intercept ctrl-c...  and (I'm assuming) that my efforts to try different :interrupt options when constructing the reader object are failing because I'm spending 99% of my time blocking in the sleep call, rather than in the read_keypress call....  so sleep is catching my ctrl-c instead of your code.

goal:  I want this loop to work as much like an ssh connection as possible.  e.g. if you hit ctrl-c in ssh, it doesn't terminate the connection, it sends the interrupt to the host and interrupts the running task.  I have the conduit, I just need the intercept.

And my app 'shutdown' issues stem from it being host initiated (I discover the end via bash `^D || exit || logout` or any other socket fatality which ends the controlling host process and tears down my sockets).  Rather than it being due to something 'predictable' that I can type, I'm notified by socket tear down.  So I can't code around the 'blocking' and exit gracefully.  The above can happen at any time 'while' blocking inside of read_keypress.

I understand the above, in that I have to be running your code in order to intercept that interrupt (if my assumption is correct)...  I've yet to find your call that blocks so terribly hard that I can't thread kill it.  If you could point me to it I'm willing to do the work in pushing down some sort of option (if available) or to otherwise think around it.

Thank you in advance!!
(It's late atm, but I'll try to contrive a simple gist tomorrow to replicate what I'd like to happen)

**Comment by piotrmurach** [comment]
I've checked running the [keypress example](https://github.com/piotrmurach/tty-reader/blob/master/examples/keypress.rb) on Windows XP, Ruby `v2.0.0` and all works fine for me, I can `ctrl-c` out of the `read_keypress`. This method parses any key in blocking, raw and non-echo mode, and when it encouters `ctrl-x` character it triggers one of the interrupt behaviours. Of course, if it fails to recognise the `ctrl-c` then it won't interrupt.

**Comment by thewyzard44** [comment]
yup ok so that we're talking apples & apples I've adapted your sample:

```ruby
#!/usr/bin/env ruby

require 'tty-reader'

reader = TTY::Reader.new interrupt: -> { puts 'interrupted' } # I would forward the ctrl-c to the host here

puts 'Press a key (or Ctrl-X to exit)'

th = Thread.new do
  loop do
    char = reader.read_keypress # nonblock: true
    unless char
      sleep 0.01
      next
    end
    print '=> '
    if ?\C-x == char
      puts 'Exiting...'
      exit
    else
      puts "#{char.inspect} [#{char.ord}] (hex: #{char.ord.to_s(16)})"
    end
  end
end

sleep 10 # simulate the user running 'bash' or something...  then they type 'logout' or whatever command exits their shell
puts 'user exit...'
th.exit # so I've detected that and now I want to exit this application
exit

# here's the issue: the application is now still running
# I have to 'press a key' now, and THEN it'll exit
# because read_keypress is still blocking even though i've killed its thread
```
so the above is pretty much what I'm after, if It would exit gracefully.  

I've also tried wrapping it in a Timeout block, but same effect.  The timeout exception won't throw until a key is pressed.

in order to get it to exit gracefully, I have to uncomment that `# nonblock: true`.  But then I lose the ability to capture that ctrl-c, because we're blocking in the sleep call, and so ruby processes the ctrl-c and kills the app rather than your code catching it and passing it to my block.

------

Confirmed: this is a WinAPI issue.  I just ran the above on linux and it works great.  I suspect that the thread is leaving ruby, entering the winapi, and blocking there, and doesn't notice our ruby exceptions or thread kills until that thread gets 'unblocked' by a keystroke and makes the return trip back into ruby.

I think some sort of :timeout option to read_keypress would solve it.  But there may be similar issues in trying to implement it.  I'll dig into that WinAPI a bit more.

**Comment by piotrmurach** [comment]
You like pain, don't you? 😄  Controlling threads through timeouts is usually a difficult task since in Ruby they are not thread-safe. I'm not really sure why you need to use threads. I would actually think that you would wish to run your commands etc... in different processes and keep full control of the keyboard input rather than let it run wild in a thread but ok. I think you're bang on money with your assumptions about controlling WinAPI calls. If you figure it out I will defo accept a patch.

**Comment by thewyzard44** [comment]
hehe no guts no glory ;)  with a timeout option, I could for sure keep everything in the main thread... including my 'connection check'.  But that's looking to be tricky to implement...  I found the root cause

https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/getch-nolock-getwch-nolock

the above says that getch actually locks the thread so that other threads can't mess with it.  So there's a lack of parity between windows & linux behavior there (as I noticed earlier).  I'm trying to figure out how to use the nolock variants atm (my first time seeing fiddle).  I tried just replacing '_getch` with `_getch_nolock` but no luck so I'm digging in...

**Comment by thewyzard44** [comment]
ok I feel silly...  I thought there was magic involved in intercepting that ctrl-c and that the app was getting tore down from within....  but no, it just pops an exception lol (I blame my ruby newbness)

I still like the idea of a :timeout option, but with the behavior of blocking in the winapi, it'd have the same problems trying to implement it inside your gem, that I had in trying to do the same outside your gem.

ultimately I'm going with
```ruby
  begin
    loop do
      break unless active.thread.alive?
      sleep 0.01 unless tty.read_keypress nonblock: true
    end
  rescue Interrupt
    # active.thread.signal 2
    active.stdin.write "\x3"
    retry
  end
```

which works beautifully...  and to implement that 'inside' your gem, would have a similar loop, with cleanup around the ctrl-c capture...  which would be ugly to say the least   lol

Thanks again! and sorry to bother

**Comment by thewyzard44** [comment]
grrr if it's not one thing then it's another...  :/  I'll figure it out  xD

```
  # TODO: ctrl-c in powershell 'works' in that it sends it to the host.  but after 'final' termination of the host process (e.g. ^D in bash) powershell annoys me with:
  #   'TERMINATE BATCH JOB (Y/N)?' (roughly) for each time that I interrupted during the session
```
